// Generated by tools/gen_argo_skin.py. Do not edit by hand.
// Source design system: @nadicodeai/design-system@0.1.0
import type { ThemeBrand, ThemeColors } from './theme.js'

export const ARGO_DARK_THEME_COLORS: ThemeColors = {
  primary: '#50e3c2',
  accent: '#007a5e',
  border: '#29bc9b',
  text: '#f2f2f2',
  muted: '#888888',
  completionBg: '#171717',
  completionCurrentBg: '#005d49',
  completionMetaBg: '#171717',
  completionMetaCurrentBg: '#007a5e',
  label: '#29bc9b',
  ok: '#008c45',
  error: '#b80022',
  warn: '#f5a623',
  prompt: '#f2f2f2',
  sessionLabel: '#29bc9b',
  sessionBorder: '#005d49',
  statusBg: '#171717',
  statusFg: '#888888',
  statusGood: '#008c45',
  statusWarn: '#f5a623',
  statusBad: '#820018',
  statusCritical: '#cd212a',
  selectionBg: '#005d49',
  diffAdded: '#008c45',
  diffRemoved: '#b80022',
  diffAddedWord: '#007a5e',
  diffRemovedWord: '#b80022',
  shellDollar: '#50e3c2',
}

export const ARGO_LIGHT_THEME_COLORS: ThemeColors = {
  primary: '#50e3c2',
  accent: '#007a5e',
  border: '#29bc9b',
  text: '#f2f2f2',
  muted: '#888888',
  completionBg: '#171717',
  completionCurrentBg: '#005d49',
  completionMetaBg: '#171717',
  completionMetaCurrentBg: '#007a5e',
  label: '#29bc9b',
  ok: '#008c45',
  error: '#b80022',
  warn: '#f5a623',
  prompt: '#f2f2f2',
  sessionLabel: '#29bc9b',
  sessionBorder: '#005d49',
  statusBg: '#171717',
  statusFg: '#888888',
  statusGood: '#008c45',
  statusWarn: '#f5a623',
  statusBad: '#820018',
  statusCritical: '#cd212a',
  selectionBg: '#005d49',
  diffAdded: '#008c45',
  diffRemoved: '#b80022',
  diffAddedWord: '#007a5e',
  diffRemovedWord: '#b80022',
  shellDollar: '#50e3c2',
}

export const ARGO_BRAND: ThemeBrand = {
  name: "Argo",
  icon: "",
  prompt: ">",
  welcome: "Type your message or /help for commands.",
  goodbye: "Goodbye.",
  tool: "|",
  helpHeader: "Commands",
}

export const ARGO_BANNER_LOGO = ""
export const ARGO_BANNER_HERO = "[#005d49]⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⡈⢳⣄⠀⠀⠀⣹⣏⠀⠀⠀⣠⡞⢁⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀[/]\n[#005d49]⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣈⡻⣦⣿⠀⠀⠀⣿⣿⠀⠀⠀⣿⣴⢟⣁⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀[/]\n[#005d49]⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⠛⠃⢸⡟⢷⣄⠀⣽⣯⠀⣠⡾⢻⡇⠘⠛⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀[/]\n[#005d49]⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠳⣄⣻⠆⣿⣿⠰⣟⣠⠞⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀[/]\n[#005d49]⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣤⣾⣿⣾⣿⣿⣷⣿⣷⣤⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀[/]\n[#007a5e]⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀[/]\n[#007a5e]⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀[/]\n[#29bc9b]⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣿⣿⣿⣿⣿⡿⠿⣿⣿⣿⣿⣿⣿⠿⢿⣿⣿⣿⣿⣿⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀[/]\n[#f2f2f2]⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣇⠀⠀⠀⠀⠀⠀⠀⠀⠀[/]\n[#f2f2f2]⠀⠀⠀⠀⠀⠀⠀⠀⢠⡟⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢻⡄⠀⠀⠀⠀⠀⠀⠀⠀[/]\n[#50e3c2]⠀⠀⠀⠀⠀⠀⠀⢀⣾⠁⠘⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠃⠈⣷⡀⠀⠀⠀⠀⠀⠀⠀[/]\n[#50e3c2]⠀⠀⠀⠀⠀⣀⣠⡾⠃⠀⠀⠀⠙⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠋⠀⠀⠀⠘⢷⣄⣀⠀⠀⠀⠀⠀[/]\n[#007a5e]⠀⠀⠀⢀⡾⠋⠁⠀⠀⠀⠀⠀⢀⠀⠈⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠁⠀⡀⠀⠀⠀⠀⠀⠈⠙⢷⡀⠀⠀⠀[/]\n[#007a5e]⠀⠀⢀⡾⠁⠀⠀⠀⠀⠀⠀⠀⠹⣆⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⣰⠏⠀⠀⠀⠀⠀⠀⠀⠈⢷⡀⠀⠀[/]\n[#005d49]⠀⠀⣼⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠳⠶⣽⣶⣤⣤⣤⣤⣶⣯⠶⠞⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⣧⠀⠀[/]\n[#005d49]⠀⢰⡏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢘⣏⣛⣛⣛⣛⣹⡃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢹⡆⠀[/]\n[#cd212a]⢀⣿⠁⠀⠀⠀⢠⣤⡄⠀⠀⠀⠀⠀⠀⠀⠀⣭⣭⣭⣭⣭⣭⠀⠀⠀⠀⠀⠀⠀⠀⢠⣤⡄⠀⠀⠀⠈⣿⡀[/]\n[#cd212a]⣼⠇⠀⠀⠀⠀⠈⠉⠁⠀⠀⠀⠀⠀⠀⠀⠀⢩⣭⣭⣭⣭⡍⠀⠀⠀⠀⠀⠀⠀⠀⠈⠉⠁⠀⠀⠀⠀⠸⣧[/]"
