# Generated by tools/gen_argo_skin.py. Do not edit by hand.
# Source design system: @nadicodeai/design-system@0.1.0
from __future__ import annotations

ARGO_SKIN_DATA = {
    "name": "argo",
    "description": "NadicodeAI ink - design-system driven",
    "colors": {
        "banner_border": "#29bc9b",
        "banner_title": "#50e3c2",
        "banner_accent": "#007a5e",
        "banner_dim": "#888888",
        "banner_text": "#f2f2f2",
        "ui_accent": "#007a5e",
        "ui_label": "#29bc9b",
        "ui_ok": "#008c45",
        "ui_error": "#cd212a",
        "ui_warn": "#f5a623",
        "prompt": "#f2f2f2",
        "input_rule": "#005d49",
        "response_border": "#50e3c2",
        "status_bar_bg": "#171717",
        "status_bar_text": "#888888",
        "status_bar_dim": "#888888",
        "status_bar_good": "#008c45",
        "status_bar_warn": "#f5a623",
        "status_bar_bad": "#820018",
        "status_bar_critical": "#cd212a",
        "status_bar_strong": "#50e3c2",
        "session_label": "#29bc9b",
        "session_border": "#005d49",
        "selection_bg": "#005d49",
        "voice_status_bg": "#171717",
        "completion_menu_bg": "#171717",
        "completion_menu_current_bg": "#005d49",
        "completion_menu_meta_bg": "#171717",
        "completion_menu_meta_current_bg": "#007a5e"
    },
    "spinner": {
        "waiting_faces": [
            "(◎)",
            "(◈)",
            "(⬡)",
            "(⊕)",
            "(⊗)"
        ],
        "thinking_faces": [
            "(◎)",
            "(◈)",
            "(⬡)",
            "(⌁)",
            "(⊗)"
        ],
        "thinking_verbs": [
            "routing",
            "reading",
            "checking",
            "mapping",
            "editing",
            "reviewing",
            "composing",
            "verifying"
        ],
        "wings": [
            [
                "⟨◎",
                "◎⟩"
            ],
            [
                "⟨◈",
                "◈⟩"
            ],
            [
                "⟨⬡",
                "⬡⟩"
            ],
            [
                "⟨⌁",
                "⌁⟩"
            ]
        ]
    },
    "branding": {
        "agent_name": "Argo",
        "welcome": "Welcome to Argo. Type your message or /help for commands.",
        "goodbye": "Goodbye.",
        "response_label": " Argo ",
        "prompt_symbol": ">",
        "status_symbol": ">",
        "help_header": "[?] Commands"
    },
    "tool_prefix": "|",
    "banner_logo": "",
    "banner_hero": "[#005d49]⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⡈⢳⣄⠀⠀⠀⣹⣏⠀⠀⠀⣠⡞⢁⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀[/]\n[#005d49]⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣈⡻⣦⣿⠀⠀⠀⣿⣿⠀⠀⠀⣿⣴⢟⣁⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀[/]\n[#005d49]⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⠛⠃⢸⡟⢷⣄⠀⣽⣯⠀⣠⡾⢻⡇⠘⠛⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀[/]\n[#005d49]⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠳⣄⣻⠆⣿⣿⠰⣟⣠⠞⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀[/]\n[#005d49]⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣤⣾⣿⣾⣿⣿⣷⣿⣷⣤⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀[/]\n[#007a5e]⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀[/]\n[#007a5e]⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀[/]\n[#29bc9b]⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣿⣿⣿⣿⣿⡿⠿⣿⣿⣿⣿⣿⣿⠿⢿⣿⣿⣿⣿⣿⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀[/]\n[#f2f2f2]⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣇⠀⠀⠀⠀⠀⠀⠀⠀⠀[/]\n[#f2f2f2]⠀⠀⠀⠀⠀⠀⠀⠀⢠⡟⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢻⡄⠀⠀⠀⠀⠀⠀⠀⠀[/]\n[#50e3c2]⠀⠀⠀⠀⠀⠀⠀⢀⣾⠁⠘⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠃⠈⣷⡀⠀⠀⠀⠀⠀⠀⠀[/]\n[#50e3c2]⠀⠀⠀⠀⠀⣀⣠⡾⠃⠀⠀⠀⠙⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠋⠀⠀⠀⠘⢷⣄⣀⠀⠀⠀⠀⠀[/]\n[#007a5e]⠀⠀⠀⢀⡾⠋⠁⠀⠀⠀⠀⠀⢀⠀⠈⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠁⠀⡀⠀⠀⠀⠀⠀⠈⠙⢷⡀⠀⠀⠀[/]\n[#007a5e]⠀⠀⢀⡾⠁⠀⠀⠀⠀⠀⠀⠀⠹⣆⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⣰⠏⠀⠀⠀⠀⠀⠀⠀⠈⢷⡀⠀⠀[/]\n[#005d49]⠀⠀⣼⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠳⠶⣽⣶⣤⣤⣤⣤⣶⣯⠶⠞⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⣧⠀⠀[/]\n[#005d49]⠀⢰⡏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢘⣏⣛⣛⣛⣛⣹⡃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢹⡆⠀[/]\n[#cd212a]⢀⣿⠁⠀⠀⠀⢠⣤⡄⠀⠀⠀⠀⠀⠀⠀⠀⣭⣭⣭⣭⣭⣭⠀⠀⠀⠀⠀⠀⠀⠀⢠⣤⡄⠀⠀⠀⠈⣿⡀[/]\n[#cd212a]⣼⠇⠀⠀⠀⠀⠈⠉⠁⠀⠀⠀⠀⠀⠀⠀⠀⢩⣭⣭⣭⣭⡍⠀⠀⠀⠀⠀⠀⠀⠀⠈⠉⠁⠀⠀⠀⠀⠸⣧[/]"
}
