"""Auto-generated rename constants for `nadia doctor --static`.

DO NOT EDIT BY HAND. Generated by ``tools/generate_rename_defaults.py``
from ``nadia-rename.yaml`` (the single source of truth). The build
pipeline (``tools/build.py``) regenerates this file before copying the
overlay into ``dist/nadia/``.

Used as a fallback by ``nadia_cli.doctor_leakage`` when no
``nadia-rename.yaml`` is available at runtime (the published
``ghcr.io/nadicodeai/nadia`` image case, where build-time config is not
shipped per spec FR-7).
"""

from __future__ import annotations

GENERATED_FROM: str = 'nadia-rename.yaml'

MAPPINGS: tuple[tuple[str, str], ...] = (
    ('NousResearch/hermes-agent/main/scripts/install', 'nadicodeai/argo/release/scripts/install'),
    ('git@github.com:nousresearch/hermes-agent', 'git@github.com:nadicodeai/argo'),
    ('github.com/nousresearch/hermes-agent', 'github.com/nadicodeai/argo'),
    ('hermes-agent.nousresearch.com/docs', 'docs.nadicode.ai/nadia'),
    ('ghcr.io/nousresearch/hermes-agent', 'ghcr.io/nadicodeai/nadia'),
    ('NousResearch/hermes-agent', 'nadicodeai/argo'),
    ('NousResearch/Hermes-Agent', 'nadicodeai/argo'),
    ('nousresearch/hermes-agent', 'ghcr.io/nadicodeai/nadia'),
    ('hermes_tools_mcp_server', 'nadia_tools_mcp_server'),
    ('hermes_bootstrap', 'nadia_bootstrap'),
    ('hermes_constants', 'nadia_constants'),
    ('hermes_logging', 'nadia_logging'),
    ('-Branch main', '-Branch release'),
    ('Hermes-Agent', 'Nadia-Agent'),
    ('hermes-agent', 'nadia-agent'),
    ('hermes_agent', 'nadia_agent'),
    ('hermes_state', 'nadia_state'),
    ('HermesAgent', 'NadiaAgent'),
    ('hermes_time', 'nadia_time'),
    ('HERMES_HOME', 'NADIA_HOME'),
    ('hermes_cli', 'nadia_cli'),
    ('~/.hermes', '~/.nadia'),
    ('.hermes/', '.nadia/'),
    ('HERMES_', 'NADIA_'),
    ('Hermes', 'Nadia'),
    ('HERMES', 'NADIA'),
    ('hermes', 'nadia'),
)

EXCEPTION_PATHS: tuple[str, ...] = (
    '.nadia/**',
    '*.egg-info/**',
    '.gitleaks.toml',
    'tests/test_full_rename_config.py',
    'nadia-xfail.yml',
    '*/_rename_defaults.py',
    'README.md',
    'README.zh-CN.md',
    'nadia-already-has-routines.md',
    '.github/workflows/skills-index.yml',
    '.github/workflows/deploy-site.yml',
)

SKIP_CONTEXTS: tuple[str, ...] = (
    'https?://(?!(?:(?:raw\\.)?github(?:usercontent)?\\.com/(?i:NousResearch/hermes-agent)\\b|hermes-agent\\.local|hermes-agent\\.nousresearch\\.com/docs\\b))[^\\s"\'\\\\${}]*',
    '\\b[0-9a-f]{40}\\b',
    '\\b[0-9a-f]{64}\\b',
    '(?i)\\bNousResearch/(?:[A-Za-z0-9_.-]+-hermes-agent|hermes-agent-[A-Za-z0-9_.-]+)\\b',
    '(?i)\\bnous[- ]hermes[\\w./-]*',
    '(?i)\\bhermes(?:[- .]?[234](?![>])[\\w.:+-]*|_[234][\\w.:+-]+)',
    'hermes\\[-_ \\]\\?\\[34\\]',
    '"hermes", "llama", "mistral"',
    'Based on Hermes Agent by Nous Research',
    'hermes-example-plugins',
    'DEFAULT_NOUS_CLIENT_ID = "hermes-cli"',
    '"client_id", "hermes-cli"',
    'default: hermes-cli',
    'hermes-cli/',
    'return "hermes-cli"',
    'hermes-cli UA',
    'product=hermes-agent',
    'client=hermes-client-v',
)

PROBE_TOKEN: str = 'hermes'
