"""Auto-generated rename constants for `argo doctor --static`.

DO NOT EDIT BY HAND. Generated by ``tools/generate_rename_defaults.py``
from ``argo-rename.yaml`` (the single source of truth). The build
pipeline (``tools/build.py``) regenerates this file before copying the
overlay into ``dist/argo/``.

Used as a fallback by ``argo_cli.doctor_leakage`` when no
``argo-rename.yaml`` is available at runtime (the published
``ghcr.io/nadicodeai/argo`` image case, where build-time config is not
shipped per spec FR-7).
"""

from __future__ import annotations

GENERATED_FROM: str = 'argo-rename.yaml'

MAPPINGS: tuple[tuple[str, str], ...] = (
    ('NousResearch/hermes-agent/main/scripts/install', 'nadicodeai/argo/release/scripts/install'),
    ('NousResearch/hermes-agent', 'nadicodeai/argo'),
    ('NousResearch/Hermes-Agent', 'nadicodeai/argo'),
    ('hermes_tools_mcp_server', 'argo_tools_mcp_server'),
    ('hermes_bootstrap', 'argo_bootstrap'),
    ('hermes_constants', 'argo_constants'),
    ('hermes_logging', 'argo_logging'),
    ('-Branch main', '-Branch release'),
    ('Hermes-Agent', 'Argo-Agent'),
    ('hermes-agent', 'argo-agent'),
    ('hermes_agent', 'argo_agent'),
    ('hermes_state', 'argo_state'),
    ('HermesAgent', 'ArgoAgent'),
    ('hermes_time', 'argo_time'),
    ('HERMES_HOME', 'ARGO_HOME'),
    ('hermes_cli', 'argo_cli'),
    ('~/.hermes', '~/.argo'),
    ('.hermes/', '.argo/'),
    ('HERMES_', 'ARGO_'),
    ('Hermes', 'Argo'),
    ('HERMES', 'ARGO'),
    ('hermes', 'argo'),
)

EXCEPTION_PATHS: tuple[str, ...] = (
    '.argo/**',
    '*.egg-info/**',
    '.gitleaks.toml',
    'tests/test_full_rename_config.py',
    'argo-xfail.yml',
    '*/_rename_defaults.py',
    'README.md',
    'README.zh-CN.md',
    'CONTRIBUTING.md',
    'AGENTS.md',
    'argo-already-has-routines.md',
    '.github/workflows/skills-index.yml',
    '.github/workflows/deploy-site.yml',
    'website/docs/developer-guide/plugin-llm-access.md',
    'website/docs/user-guide/features/extending-the-dashboard.md',
)

SKIP_CONTEXTS: tuple[str, ...] = (
    'https?://(?!(?:(?:raw\\.)?github(?:usercontent)?\\.com/(?i:NousResearch/hermes-agent)\\b|hermes-agent\\.local))[^\\s"\'\\\\]*',
    '\\b[0-9a-f]{40}\\b',
    '\\b[0-9a-f]{64}\\b',
    '(?i)\\bnous[- ]hermes[\\w./-]*',
    '(?i)\\bhermes(?:[- .]?[234][\\w.:+-]*|_[234][\\w.:+-]+)',
    'hermes\\[-_ \\]\\?\\[34\\]',
    'Based on Hermes Agent by Nous Research',
)

PROBE_TOKEN: str = 'hermes'
